#include "lvgl.h"

// These symbols are generated by EMBED_FILES in CMake.
extern const uint8_t png_start[] asm("_binary_screenshot1_png_start");
extern const uint8_t png_end[]   asm("_binary_screenshot1_png_end");

lv_img_dsc_t stick_bg_png;  // filled at runtime

void stick_bg_prepare(void) {
    stick_bg_png.header.always_zero = 0;
    stick_bg_png.header.w = 0;    // unknown until decoded
    stick_bg_png.header.h = 0;    // unknown until decoded
    stick_bg_png.data_size = (uint32_t)(png_end - png_start);
    stick_bg_png.header.cf = LV_IMG_CF_RAW_ALPHA; // Let LVGL PNG decoder handle it
    stick_bg_png.data = (const uint8_t *)png_start;
}


